import WeilAutocorrelationMellinV11

#check AEGIS.WeilAutocorrelationMellinV11.centered_transform_eq_mellin_v11
#check AEGIS.WeilAutocorrelationMellinV11.centered_correlation_transform_factorization_v11
#check AEGIS.WeilAutocorrelationMellinV11.weil_autocorrelation_mellin_factorization_v11

#print axioms AEGIS.WeilAutocorrelationMellinV11.centered_correlation_transform_factorization_v11
#print axioms AEGIS.WeilAutocorrelationMellinV11.weil_autocorrelation_mellin_factorization_v11
