import Mathlib.Analysis.SpecialFunctions.Integrals.Basic
import Mathlib.Tactic

/-!
AEGIS Ω — finite single-frequency source calculus v1.

This file proves the finite algebra/analysis identity underlying the
single-frequency step of the Guinand--Weil source calculus.

For

  ψ_{α,ω}(x) = (α / π) sin(2 π ω x),

the divided-difference entry of the source is exactly α times the real
termwise Volterra/chord contribution. Summing over a finite frequency band
therefore identifies the finite quadratic contraction with α times the
expanded real chord kernel.

`WeilChordKernelV1` is deliberately the finite real termwise expansion. This
file does NOT yet prove its equality with the real part of the single compact
integral `2 ∫ T(t) T(ω-t) dt`; that finite-sum/integral interchange and the
even-symmetry cancellation can be added as a separate strengthening without
changing any theorem proved here.

No zeta-zero statement, PSD claim, global Weil positivity, or RH claim is made.
-/

open scoped BigOperators
open intervalIntegral

set_option autoImplicit false

noncomputable section

/-- One sinusoidal source atom in the finite Guinand--Weil source calculus. -/
def WeilSingleFrequencySourceV1 (α ω x : ℝ) : ℝ :=
  α / Real.pi * Real.sin (2 * Real.pi * ω * x)

/-- The divided-difference matrix entry generated by one sinusoidal source.
The diagonal is the derivative value. -/
def WeilSingleFrequencyEntryV1 (α ω : ℝ) (m n : ℤ) : ℝ :=
  if m = n then
    2 * α * ω * Real.cos (2 * Real.pi * ω * (m : ℝ))
  else
    (WeilSingleFrequencySourceV1 α ω (m : ℝ) -
      WeilSingleFrequencySourceV1 α ω (n : ℝ)) /
      ((m : ℝ) - (n : ℝ))

/-- The finite complex trigonometric polynomial used by the paper-level
Volterra construction. It is exposed here to freeze the intended carrier;
the v1 theorem below works with the exactly equivalent termwise real
expansion and therefore does not need a sum/integral interchange. -/
def WeilTrigPolynomialV1 (N : ℕ) (u : ℤ → ℝ) (t : ℝ) : ℂ :=
  ∑ m ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
    (u m : ℂ) * Complex.exp
      ((2 * Real.pi * (m : ℝ) * t : ℝ) * Complex.I)

/-- Real contribution of the ordered pair `(m,n)` to the expanded chord
kernel. -/
def WeilChordPairV1 (ω : ℝ) (m n : ℤ) : ℝ :=
  2 * ∫ t in (0 : ℝ)..ω,
    Real.cos
      (2 * Real.pi *
        (((m : ℝ) - (n : ℝ)) * t + (n : ℝ) * ω))

/-- Finite real termwise Volterra/chord kernel on the symmetric band. -/
def WeilChordKernelV1 (N : ℕ) (u : ℤ → ℝ) (ω : ℝ) : ℝ :=
  ∑ m ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
    ∑ n ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
      u m * u n * WeilChordPairV1 ω m n

/-- Finite quadratic contraction of the one-frequency divided-difference
matrix. -/
def WeilSingleFrequencyQuadraticV1
    (N : ℕ) (u : ℤ → ℝ) (α ω : ℝ) : ℝ :=
  ∑ m ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
    ∑ n ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
      u m * u n * WeilSingleFrequencyEntryV1 α ω m n

private theorem integral_cos_affine_v1
    (A B a b : ℝ) (hA : A ≠ 0) :
    (∫ t in a..b, Real.cos (A * t + B)) =
      (Real.sin (A * b + B) - Real.sin (A * a + B)) / A := by
  rw [sub_div]
  apply integral_eq_sub_of_hasDerivAt
  swap
  · exact (Real.continuous_cos.comp
      ((continuous_const.mul continuous_id).add continuous_const)).intervalIntegrable a b
  intro x _
  have hlin : HasDerivAt (fun y : ℝ => A * y + B) A x := by
    simpa using ((hasDerivAt_id x).const_mul A).add_const B
  have hsin := (Real.hasDerivAt_sin (A * x + B)).comp x hlin
  simpa [hA] using hsin.div_const A

/-- Off the diagonal, the real Volterra pair integral is exactly the source
divided difference. -/
theorem weil_single_frequency_source_offdiag_v1
    (α ω : ℝ) (m n : ℤ) (hmn : m ≠ n) :
    WeilSingleFrequencyEntryV1 α ω m n =
      α * WeilChordPairV1 ω m n := by
  have hmnR : (m : ℝ) ≠ (n : ℝ) := by exact_mod_cast hmn
  have hd : (m : ℝ) - (n : ℝ) ≠ 0 := sub_ne_zero.mpr hmnR
  have hA : 2 * Real.pi * ((m : ℝ) - (n : ℝ)) ≠ 0 := by
    exact mul_ne_zero (mul_ne_zero (by norm_num) Real.pi_ne_zero) hd
  have hfun :
      (fun t : ℝ =>
        Real.cos
          (2 * Real.pi * (((m : ℝ) - (n : ℝ)) * t + (n : ℝ) * ω))) =
      (fun t : ℝ =>
        Real.cos
          ((2 * Real.pi * ((m : ℝ) - (n : ℝ))) * t +
            2 * Real.pi * (n : ℝ) * ω)) := by
    funext t
    congr 1
    ring
  have hmarg :
      (2 * Real.pi * ((m : ℝ) - (n : ℝ))) * ω +
          2 * Real.pi * (n : ℝ) * ω =
        2 * Real.pi * ω * (m : ℝ) := by
    ring
  have hnarg :
      (2 * Real.pi * ((m : ℝ) - (n : ℝ))) * 0 +
          2 * Real.pi * (n : ℝ) * ω =
        2 * Real.pi * ω * (n : ℝ) := by
    ring
  rw [WeilSingleFrequencyEntryV1, if_neg hmn]
  unfold WeilChordPairV1
  rw [hfun]
  rw [integral_cos_affine_v1
    (2 * Real.pi * ((m : ℝ) - (n : ℝ)))
    (2 * Real.pi * (n : ℝ) * ω) 0 ω hA]
  rw [hmarg, hnarg]
  unfold WeilSingleFrequencySourceV1
  field_simp [Real.pi_ne_zero, hd]

/-- On the diagonal, the same pair integral is the derivative entry. -/
theorem weil_single_frequency_source_diagonal_v1
    (α ω : ℝ) (m : ℤ) :
    WeilSingleFrequencyEntryV1 α ω m m =
      α * WeilChordPairV1 ω m m := by
  have harg :
      2 * Real.pi * ω * (m : ℝ) =
        2 * Real.pi * ((m : ℝ) * ω) := by
    ring
  simp [WeilSingleFrequencyEntryV1, WeilChordPairV1, harg] <;> ring

private theorem weil_single_frequency_entry_eq_chord_pair_v1
    (α ω : ℝ) (m n : ℤ) :
    WeilSingleFrequencyEntryV1 α ω m n =
      α * WeilChordPairV1 ω m n := by
  by_cases hmn : m = n
  · subst n
    exact weil_single_frequency_source_diagonal_v1 α ω m
  · exact weil_single_frequency_source_offdiag_v1 α ω m n hmn

/-- Finite source calculus, in its exact real termwise Volterra form:
the quadratic contraction of a one-frequency divided-difference matrix equals
`α` times the expanded chord kernel. -/
theorem weil_single_frequency_source_calculus_v1
    (N : ℕ) (u : ℤ → ℝ) (α ω : ℝ) :
    WeilSingleFrequencyQuadraticV1 N u α ω =
      α * WeilChordKernelV1 N u ω := by
  simp only [WeilSingleFrequencyQuadraticV1, WeilChordKernelV1]
  simp_rw [weil_single_frequency_entry_eq_chord_pair_v1]
  simp [Finset.mul_sum, mul_left_comm, mul_comm]

/-- A finite atomic real source, represented by finitely many masses `α i`
at frequencies `ω i`.  No positivity or support restriction is required. -/
def WeilFiniteSourceV1
    {ι : Type*} (I : Finset ι) (α ω : ι → ℝ) (x : ℝ) : ℝ :=
  ∑ i ∈ I, WeilSingleFrequencySourceV1 (α i) (ω i) x

/-- Entrywise finite-source superposition. -/
def WeilFiniteSourceEntryV1
    {ι : Type*} (I : Finset ι) (α ω : ι → ℝ) (m n : ℤ) : ℝ :=
  ∑ i ∈ I, WeilSingleFrequencyEntryV1 (α i) (ω i) m n

/-- Quadratic value of a finite atomic source, represented as the finite sum of
the already-proved single-frequency quadratic values. -/
def WeilFiniteSourceQuadraticByAtomsV1
    {ι : Type*} (I : Finset ι) (N : ℕ) (u : ℤ → ℝ)
    (α ω : ι → ℝ) : ℝ :=
  ∑ i ∈ I, WeilSingleFrequencyQuadraticV1 N u (α i) (ω i)

/-- The same finite source contracted as one summed entry matrix. -/
def WeilFiniteSourceQuadraticFromEntryV1
    {ι : Type*} (I : Finset ι) (N : ℕ) (u : ℤ → ℝ)
    (α ω : ι → ℝ) : ℝ :=
  ∑ m ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
    ∑ n ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
      u m * u n * WeilFiniteSourceEntryV1 I α ω m n

/-- Finite atomic source evaluated through the expanded chord kernel. -/
def WeilFiniteSourceChordV1
    {ι : Type*} (I : Finset ι) (N : ℕ) (u : ℤ → ℝ)
    (α ω : ι → ℝ) : ℝ :=
  ∑ i ∈ I, α i * WeilChordKernelV1 N u (ω i)

/-- Finite-source-measure extension of the single-frequency calculus. -/
theorem weil_finite_source_measure_extension_v1
    {ι : Type*} (I : Finset ι) (N : ℕ) (u : ℤ → ℝ)
    (α ω : ι → ℝ) :
    WeilFiniteSourceQuadraticByAtomsV1 I N u α ω =
      WeilFiniteSourceChordV1 I N u α ω := by
  simp [WeilFiniteSourceQuadraticByAtomsV1, WeilFiniteSourceChordV1,
    weil_single_frequency_source_calculus_v1]

/-- Full finite-source entry identification: contracting the one matrix obtained
by summing all atomic entries equals the sum of the already-proved atomic
quadratic contractions.  This is finite linear algebra only. -/
theorem weil_finite_source_full_entry_identification_v1
    {ι : Type*} (I : Finset ι) (N : ℕ) (u : ℤ → ℝ)
    (α ω : ι → ℝ) :
    WeilFiniteSourceQuadraticFromEntryV1 I N u α ω =
      WeilFiniteSourceQuadraticByAtomsV1 I N u α ω := by
  classical
  simp only [WeilFiniteSourceQuadraticFromEntryV1, WeilFiniteSourceEntryV1,
    WeilFiniteSourceQuadraticByAtomsV1, WeilSingleFrequencyQuadraticV1]
  simp_rw [Finset.mul_sum]
  calc
    (∑ m ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
      ∑ n ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
        ∑ i ∈ I,
          u m * u n * WeilSingleFrequencyEntryV1 (α i) (ω i) m n) =
      ∑ m ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
        ∑ i ∈ I,
          ∑ n ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
            u m * u n * WeilSingleFrequencyEntryV1 (α i) (ω i) m n := by
      apply Finset.sum_congr rfl
      intro m hm
      rw [Finset.sum_comm]
    _ =
      ∑ i ∈ I,
        ∑ m ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
          ∑ n ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
            u m * u n * WeilSingleFrequencyEntryV1 (α i) (ω i) m n := by
      rw [Finset.sum_comm]

/-- Prime-entry kernel used by the production Arb evaluator before the outer
prime weight is subtracted from the assembled matrix.  The parameter `r`
corresponds to `log(q) / L`; the canonical source frequency is `1-r`. -/
def WeilPrimeEvaluatorKernelV1 (r : ℝ) (m n : ℤ) : ℝ :=
  if m = n then
    2 * (1 - r) * Real.cos (2 * Real.pi * r * (m : ℝ))
  else
    (Real.sin (2 * Real.pi * r * (m : ℝ)) -
      Real.sin (2 * Real.pi * r * (n : ℝ))) /
      (Real.pi * ((n : ℝ) - (m : ℝ)))

private theorem weil_sin_one_sub_at_int_v1 (r : ℝ) (m : ℤ) :
    Real.sin (2 * Real.pi * (1 - r) * (m : ℝ)) =
      -Real.sin (2 * Real.pi * r * (m : ℝ)) := by
  have harg :
      2 * Real.pi * (1 - r) * (m : ℝ) =
        (m : ℝ) * (2 * Real.pi) - 2 * Real.pi * r * (m : ℝ) := by
    ring
  rw [harg]
  simpa [mul_assoc, mul_comm, mul_left_comm] using
    Real.sin_int_mul_two_pi_sub (2 * Real.pi * r * (m : ℝ)) m

private theorem weil_cos_one_sub_at_int_v1 (r : ℝ) (m : ℤ) :
    Real.cos (2 * Real.pi * (1 - r) * (m : ℝ)) =
      Real.cos (2 * Real.pi * r * (m : ℝ)) := by
  have harg :
      2 * Real.pi * (1 - r) * (m : ℝ) =
        (m : ℝ) * (2 * Real.pi) - 2 * Real.pi * r * (m : ℝ) := by
    ring
  rw [harg]
  simpa [mul_assoc, mul_comm, mul_left_comm] using
    Real.cos_int_mul_two_pi_sub (2 * Real.pi * r * (m : ℝ)) m

/-- Canonical prime-source atom to production-evaluator entry identity.
For `beta = Lambda(q)/sqrt(q)` and `r = log(q)/L`, the source atom has
`alpha = -beta` and `omega = 1-r`; its integer Galerkin entry is exactly the
negative weighted evaluator kernel. -/
theorem weil_prime_atom_entry_matches_evaluator_v1
    (β r : ℝ) (m n : ℤ) :
    WeilSingleFrequencyEntryV1 (-β) (1 - r) m n =
      -β * WeilPrimeEvaluatorKernelV1 r m n := by
  by_cases hmn : m = n
  · subst n
    rw [WeilSingleFrequencyEntryV1, if_pos rfl]
    rw [WeilPrimeEvaluatorKernelV1, if_pos rfl]
    rw [weil_cos_one_sub_at_int_v1]
    ring
  · have hmnR : (m : ℝ) ≠ (n : ℝ) := by exact_mod_cast hmn
    have hnmR : (n : ℝ) ≠ (m : ℝ) := Ne.symm hmnR
    have hmn0 : (m : ℝ) - (n : ℝ) ≠ 0 := sub_ne_zero.mpr hmnR
    have hnm0 : (n : ℝ) - (m : ℝ) ≠ 0 := sub_ne_zero.mpr hnmR
    rw [WeilSingleFrequencyEntryV1, if_neg hmn]
    rw [WeilPrimeEvaluatorKernelV1, if_neg hmn]
    unfold WeilSingleFrequencySourceV1
    rw [weil_sin_one_sub_at_int_v1, weil_sin_one_sub_at_int_v1]
    field_simp [Real.pi_ne_zero, hmn0, hnm0]
    ring

/-- Rational source core whose divided differences split into two Cauchy
feature products.  This is the algebraic core used by the Archimedean tail
rank-two Gram representation; no analytic source identification is asserted. -/
def WeilCauchySourceCoreV1 (a x : ℝ) : ℝ :=
  x / (a ^ 2 - x ^ 2)

/-- The rank-two Cauchy entry generated by the left/right poles `-x` and `x`.
The factor `1/2` is the scalar weight that turns the two feature products into
the divided difference of `x/(a^2-x^2)`. -/
def WeilCauchyRankTwoEntryV1 (a m n : ℝ) : ℝ :=
  (1 / 2 : ℝ) *
    ((1 / (a - m)) * (1 / (a - n)) +
      (1 / (a + m)) * (1 / (a + n)))

/-- The diagonal derivative value of the rational Cauchy source core. -/
def WeilCauchyDiagonalV1 (a m : ℝ) : ℝ :=
  (a ^ 2 + m ^ 2) / (a ^ 2 - m ^ 2) ^ 2

/-- Off the diagonal, the divided difference of `x/(a^2-x^2)` is exactly the
rank-two Cauchy feature-product entry. -/
theorem weil_cauchy_divided_difference_rank_two_v1
    (a m n : ℝ)
    (ham : a - m ≠ 0) (hapm : a + m ≠ 0)
    (han : a - n ≠ 0) (hapn : a + n ≠ 0)
    (hmn : m ≠ n) :
    (WeilCauchySourceCoreV1 a m - WeilCauchySourceCoreV1 a n) /
        (m - n) =
      WeilCauchyRankTwoEntryV1 a m n := by
  have hdm : a ^ 2 - m ^ 2 ≠ 0 := by
    rw [show a ^ 2 - m ^ 2 = (a - m) * (a + m) by ring]
    exact mul_ne_zero ham hapm
  have hdn : a ^ 2 - n ^ 2 ≠ 0 := by
    rw [show a ^ 2 - n ^ 2 = (a - n) * (a + n) by ring]
    exact mul_ne_zero han hapn
  have hmn0 : m - n ≠ 0 := sub_ne_zero.mpr hmn
  unfold WeilCauchySourceCoreV1 WeilCauchyRankTwoEntryV1
  field_simp [hdm, hdn, hmn0, ham, hapm, han, hapn]
  ring

/-- On the diagonal, the derivative entry is the same rank-two feature-product
sum specialized to equal coordinates. -/
theorem weil_cauchy_diagonal_rank_two_v1
    (a m : ℝ) (ham : a - m ≠ 0) (hapm : a + m ≠ 0) :
    WeilCauchyDiagonalV1 a m = WeilCauchyRankTwoEntryV1 a m m := by
  have hdm : a ^ 2 - m ^ 2 ≠ 0 := by
    rw [show a ^ 2 - m ^ 2 = (a - m) * (a + m) by ring]
    exact mul_ne_zero ham hapm
  unfold WeilCauchyDiagonalV1 WeilCauchyRankTwoEntryV1
  field_simp [hdm, ham, hapm]
  ring

#print axioms weil_single_frequency_source_offdiag_v1
#print axioms weil_single_frequency_source_diagonal_v1
#print axioms weil_single_frequency_source_calculus_v1
#print axioms weil_finite_source_measure_extension_v1
#print axioms weil_finite_source_full_entry_identification_v1
#print axioms weil_prime_atom_entry_matches_evaluator_v1
#print axioms weil_cauchy_divided_difference_rank_two_v1
#print axioms weil_cauchy_diagonal_rank_two_v1

/-- Finite real quadratic contraction of the rank-two Cauchy entry kernel. -/
def WeilCauchyFiniteQuadraticV1
    {ι : Type*} (I : Finset ι) (a : ℝ) (x u : ι → ℝ) : ℝ :=
  ∑ i ∈ I, ∑ j ∈ I,
    u i * u j * WeilCauchyRankTwoEntryV1 a (x i) (x j)

/-- Left Cauchy feature moment. -/
def WeilCauchyMinusMomentV1
    {ι : Type*} (I : Finset ι) (a : ℝ) (x u : ι → ℝ) : ℝ :=
  ∑ i ∈ I, u i * (1 / (a - x i))

/-- Right Cauchy feature moment. -/
def WeilCauchyPlusMomentV1
    {ι : Type*} (I : Finset ι) (a : ℝ) (x u : ι → ℝ) : ℝ :=
  ∑ i ∈ I, u i * (1 / (a + x i))

private theorem finset_double_sum_mul_eq_sq_v1
    {ι : Type*} (I : Finset ι) (v : ι → ℝ) :
    (∑ i ∈ I, ∑ j ∈ I, v i * v j) =
      (∑ i ∈ I, v i) ^ 2 := by
  rw [pow_two, Finset.sum_mul]
  apply Finset.sum_congr rfl
  intro i hi
  rw [Finset.mul_sum]

/-- The finite rank-two Cauchy quadratic is exactly one half of the sum of the
squares of its two feature moments.  This is the real-carrier analogue of the
finite Gram core used by #322; it imports no positivity claim from that Coq
lane and needs no nonresonance hypothesis because real division is total. -/
theorem weil_cauchy_finite_quadratic_sum_squares_v1
    {ι : Type*} (I : Finset ι) (a : ℝ) (x u : ι → ℝ) :
    WeilCauchyFiniteQuadraticV1 I a x u =
      (1 / 2 : ℝ) *
        (WeilCauchyMinusMomentV1 I a x u ^ 2 +
          WeilCauchyPlusMomentV1 I a x u ^ 2) := by
  classical
  have hsplit :
      WeilCauchyFiniteQuadraticV1 I a x u =
        (1 / 2 : ℝ) *
          ((∑ i ∈ I, ∑ j ∈ I,
              (u i * (1 / (a - x i))) *
                (u j * (1 / (a - x j)))) +
            (∑ i ∈ I, ∑ j ∈ I,
              (u i * (1 / (a + x i))) *
                (u j * (1 / (a + x j))))) := by
    unfold WeilCauchyFiniteQuadraticV1
    calc
      (∑ i ∈ I, ∑ j ∈ I,
        u i * u j * WeilCauchyRankTwoEntryV1 a (x i) (x j)) =
          ∑ i ∈ I, ∑ j ∈ I,
            ((1 / 2 : ℝ) *
              ((u i * (1 / (a - x i))) *
                (u j * (1 / (a - x j)))) +
             (1 / 2 : ℝ) *
              ((u i * (1 / (a + x i))) *
                (u j * (1 / (a + x j))))) := by
            apply Finset.sum_congr rfl
            intro i hi
            apply Finset.sum_congr rfl
            intro j hj
            unfold WeilCauchyRankTwoEntryV1
            ring
      _ = (1 / 2 : ℝ) *
          ((∑ i ∈ I, ∑ j ∈ I,
              (u i * (1 / (a - x i))) *
                (u j * (1 / (a - x j)))) +
            (∑ i ∈ I, ∑ j ∈ I,
              (u i * (1 / (a + x i))) *
                (u j * (1 / (a + x j))))) := by
            simp_rw [Finset.sum_add_distrib, ← Finset.mul_sum]
            ring
  rw [hsplit]
  have hminus := finset_double_sum_mul_eq_sq_v1 I
    (fun i => u i * (1 / (a - x i)))
  have hplus := finset_double_sum_mul_eq_sq_v1 I
    (fun i => u i * (1 / (a + x i)))
  rw [hminus, hplus]
  rfl

/-- Real-carrier finite rank-two Cauchy PSD theorem. -/
theorem weil_cauchy_finite_quadratic_nonnegative_v1
    {ι : Type*} (I : Finset ι) (a : ℝ) (x u : ι → ℝ) :
    0 ≤ WeilCauchyFiniteQuadraticV1 I a x u := by
  rw [weil_cauchy_finite_quadratic_sum_squares_v1]
  positivity

/-- Compatibility name for the rank-two quadratic nonnegativity boundary. -/
theorem weil_cauchy_rank_two_quadratic_nonnegative_v1
    {ι : Type*} (I : Finset ι) (a : ℝ) (x u : ι → ℝ) :
    0 ≤ WeilCauchyFiniteQuadraticV1 I a x u :=
  weil_cauchy_finite_quadratic_nonnegative_v1 I a x u

#print axioms weil_cauchy_finite_quadratic_sum_squares_v1
#print axioms weil_cauchy_finite_quadratic_nonnegative_v1
#print axioms weil_cauchy_rank_two_quadratic_nonnegative_v1
