import WeilThreeBlockCrossAssemblyV30
import Mathlib.MeasureTheory.Integral.Prod

/-!
Separated Archimedean bridge for the actual mixed correlation.
Moment transport below derives the weighted correlation integral from the
repository moments, including compact support and the Fubini justification.
No global Weil sign or RH conclusion is asserted.
-/

open Set Function MeasureTheory Complex
open scoped ComplexConjugate BigOperators
set_option autoImplicit false
noncomputable section
namespace AEGIS.WeilSeparatedArchBridgeV31

/-- Total width of the support-difference / correlation interval generated by
two retained packet supports. Each packet has total log-width 1/32, so the
difference interval has total width 1/16. -/
def CorrelationSupportDifferenceWidthV31 : ℝ := (1 : ℝ) / 16

theorem twice_packet_width_eq_correlation_width_v31 :
    2 * ((1 : ℝ) / 32) = CorrelationSupportDifferenceWidthV31 := by
  norm_num [CorrelationSupportDifferenceWidthV31]

open AEGIS.WeilMixedClosureV2
open AEGIS.WeilLogCoordinateIsometryV21
open AEGIS.WeilThreeBlockTranslatedPacketsV22
open AEGIS.WeilThreeBlockCrossPrimeV28

theorem logLift_continuous (p : WeilCompactSmoothGV1) :
    Continuous (logLift p.1) := by
  unfold logLift
  exact (by fun_prop : Continuous (fun t : ℝ => (Real.exp (t / 2) : ℂ))).mul
    (p.2.1.continuous.comp Real.continuous_exp)

theorem logCross_continuous (p q : WeilCompactSmoothGV1) :
    Continuous (logCrossV28 p q) := by
  change Continuous (fun u : ℝ => logCrossV28 p q u)
  simp_rw [logCross_eq_mixed_v28]
  exact (by fun_prop : Continuous (fun u : ℝ => (Real.exp (u / 2) : ℂ))).mul
    ((smooth p q).continuous.comp Real.continuous_exp)

theorem logCross_zero_outside
    (p q : WeilCompactSmoothGV1) (plo phi qlo qhi u : ℝ)
    (hp : LogSupportIn p plo phi) (hq : LogSupportIn q qlo qhi)
    (hu : u < plo - qhi ∨ phi - qlo < u) : logCrossV28 p q u = 0 := by
  unfold logCrossV28
  apply integral_eq_zero_of_ae
  filter_upwards [] with v
  by_cases hp0 : logLift p.1 (v + u) = 0
  · simp [hp0]
  by_cases hq0 : logLift q.1 v = 0
  · simp [hq0]
  have hpI := hp (subset_tsupport _ hp0)
  have hqI := hq (subset_tsupport _ hq0)
  exfalso
  rcases hu with hu | hu <;> linarith [hpI.1, hpI.2, hqI.1, hqI.2]

def weightedCrossIntegrand
    (p q : WeilCompactSmoothGV1) (lam : ℝ) (z : ℝ × ℝ) : ℂ :=
  (Real.exp (lam * z.1) : ℂ) * logLift p.1 (z.2 + z.1) * conj (logLift q.1 z.2)

theorem weightedCrossIntegrand_integrable
    (p q : WeilCompactSmoothGV1) (lam plo phi qlo qhi : ℝ)
    (hp : LogSupportIn p plo phi) (hq : LogSupportIn q qlo qhi) :
    Integrable (weightedCrossIntegrand p q lam) (volume.prod volume) := by
  have hc : Continuous (weightedCrossIntegrand p q lam) := by
    unfold weightedCrossIntegrand
    exact ((by fun_prop : Continuous (fun z : ℝ × ℝ =>
      (Real.exp (lam * z.1) : ℂ))).mul
      ((logLift_continuous p).comp (continuous_snd.add continuous_fst))).mul
      (continuous_conj.comp ((logLift_continuous q).comp continuous_snd))
  have hk : HasCompactSupport (weightedCrossIntegrand p q lam) := by
    apply HasCompactSupport.of_support_subset_isCompact
      ((isCompact_Icc : IsCompact (Icc (plo - qhi) (phi - qlo))).prod
        (isCompact_Icc : IsCompact (Icc qlo qhi)))
    intro z hz
    have hp0 : logLift p.1 (z.2 + z.1) ≠ 0 := by
      intro h
      exact hz (by simp [weightedCrossIntegrand, h])
    have hq0 : logLift q.1 z.2 ≠ 0 := by
      intro h
      exact hz (by simp [weightedCrossIntegrand, h])
    have hpI := hp (subset_tsupport _ hp0)
    have hqI := hq (subset_tsupport _ hq0)
    exact ⟨⟨by linarith [hpI.1, hqI.2], by linarith [hpI.2, hqI.1]⟩, hqI⟩
  exact hc.integrable_of_hasCompactSupport hk

theorem weighted_logCross_integrable
    (p q : WeilCompactSmoothGV1) (lam plo phi qlo qhi : ℝ)
    (hp : LogSupportIn p plo phi) (hq : LogSupportIn q qlo qhi) :
    Integrable (fun u : ℝ => (Real.exp (lam * u) : ℂ) * logCrossV28 p q u) := by
  have hi := (weightedCrossIntegrand_integrable p q lam plo phi qlo qhi hp hq).integral_prod_left
  simpa only [weightedCrossIntegrand, logCrossV28, mul_assoc, integral_const_mul] using hi

/-- Fubini and additive translation transport a zero weighted packet moment
to a zero weighted mixed-correlation moment. -/
theorem weighted_logCross_moment_zero
    (p q : WeilCompactSmoothGV1) (lam plo phi qlo qhi : ℝ)
    (hp : LogSupportIn p plo phi) (hq : LogSupportIn q qlo qhi)
    (hm : (∫ s : ℝ, (Real.exp (lam * s) : ℂ) * logLift p.1 s) = 0) :
    (∫ u : ℝ, (Real.exp (lam * u) : ℂ) * logCrossV28 p q u) = 0 := by
  have hi := weightedCrossIntegrand_integrable p q lam plo phi qlo qhi hp hq
  calc
    (∫ u : ℝ, (Real.exp (lam * u) : ℂ) * logCrossV28 p q u) =
        ∫ u : ℝ, ∫ v : ℝ, weightedCrossIntegrand p q lam (u, v) := by
      simp only [weightedCrossIntegrand, logCrossV28, mul_assoc, integral_const_mul]
    _ = ∫ v : ℝ, ∫ u : ℝ, weightedCrossIntegrand p q lam (u, v) :=
      integral_integral_swap hi
    _ = 0 := by
      apply integral_eq_zero_of_ae
      filter_upwards [] with v
      have he (u : ℝ) : Real.exp (lam * u) =
          Real.exp (-lam * v) * Real.exp (lam * (u + v)) := by
        rw [← Real.exp_add]
        congr 1
        ring
      have hinner : (∫ u : ℝ, weightedCrossIntegrand p q lam (u, v)) =
          (Real.exp (-lam * v) : ℂ) *
            (∫ u : ℝ, (Real.exp (lam * (u + v)) : ℂ) * logLift p.1 (u + v)) *
              conj (logLift q.1 v) := by
        erw [← integral_const_mul, ← integral_mul_const]
        apply integral_congr_ae
        filter_upwards [] with u
        unfold weightedCrossIntegrand
        rw [he u, Complex.ofReal_mul, add_comm v u]
        ring
      have hshift := integral_add_right_eq_self (μ := volume)
        (fun s : ℝ => (Real.exp (lam * s) : ℂ) * logLift p.1 s) v
      erw [hinner, hshift, hm, mul_zero, zero_mul]
      rfl

theorem logCross_plus_moment_zero
    (p q : WeilCompactSmoothGV1) (plo phi qlo qhi : ℝ)
    (hp : LogSupportIn p plo phi) (hq : LogSupportIn q qlo qhi)
    (hm : WeilMomentConditionsV1 p) :
    (∫ u : ℝ, (Real.exp (u / 2) : ℂ) * logCrossV28 p q u) = 0 := by
  have hz : (∫ s : ℝ, (Real.exp ((1 / 2 : ℝ) * s) : ℂ) * logLift p.1 s) = 0 := by
    simpa only [one_div_mul_eq_div, logMomentPlus] using
      (logMomentPlus_eq_repository p).trans hm.2
  simpa only [one_div_mul_eq_div] using
    weighted_logCross_moment_zero p q (1 / 2) plo phi qlo qhi hp hq hz

theorem logCross_minus_moment_zero
    (p q : WeilCompactSmoothGV1) (plo phi qlo qhi : ℝ)
    (hp : LogSupportIn p plo phi) (hq : LogSupportIn q qlo qhi)
    (hm : WeilMomentConditionsV1 p) :
    (∫ u : ℝ, (Real.exp (-u / 2) : ℂ) * logCrossV28 p q u) = 0 := by
  have hn (s : ℝ) : (-1 / 2 : ℝ) * s = -s / 2 := by ring
  have hz : (∫ s : ℝ, (Real.exp ((-1 / 2 : ℝ) * s) : ℂ) * logLift p.1 s) = 0 := by
    simpa only [hn, logMomentMinus] using (logMomentMinus_eq_repository p).trans hm.1
  simpa only [hn] using weighted_logCross_moment_zero p q (-1 / 2) plo phi qlo qhi hp hq hz

private theorem kernel_algebra (x y z w m : ℂ)
    (hx : x ≠ 0) (hd : 1 - w ≠ 0)
    (hy : y = x⁻¹) (hz : z * z = y) (hw : x * w = y) :
    x * ((1 / x * m) / (x - y)) = z / (1 - w) * (z * m) := by
  have hden : x - y = x * (1 - w) := by rw [mul_sub, mul_one, hw]
  calc
    x * ((1 / x * m) / (x - y)) = x⁻¹ * m / (1 - w) := by
      rw [hden]
      field_simp [hx, hd]
      <;> ring
    _ = y * m / (1 - w) := by rw [hy]
    _ = z / (1 - w) * (z * m) := by rw [← hz]; ring

/-- Exact conversion of the repository Archimedean integral for strictly
ordered logarithmic supports. Both centre and positive-displacement terms
vanish by support; the surviving term has the stated negative log shift. -/
theorem separated_arch_eq_log_kernel
    (p q : WeilCompactSmoothGV1) (plo phi qlo qhi : ℝ)
    (hp : LogSupportIn p plo phi) (hq : LogSupportIn q qlo qhi)
    (hsep : phi < qlo) :
    WeilArchimedeanIntegralV1 (mixed p q) =
      ∫ u in Ioi (0 : ℝ),
        ((Real.exp (-u / 2) / (1 - Real.exp (-2 * u)) : ℝ) : ℂ) *
          logCrossV28 p q (-u) := by
  have hzero (u : ℝ) (hu : 0 ≤ u) : mixed p q (Real.exp u) = 0 := by
    have hc := logCross_zero_outside p q plo phi qlo qhi u hp hq
      (Or.inr (by linarith))
    rw [logCross_eq_mixed_v28] at hc
    exact (mul_eq_zero.mp hc).resolve_left (by simp)
  have hcenter : mixed p q 1 = 0 := by simpa using hzero 0 le_rfl
  unfold WeilArchimedeanIntegralV1
  rw [← show (∫ u in Ioi (0 : ℝ), Real.exp u •
      WeilArchimedeanIntegrandV1 (mixed p q) (Real.exp u)) =
        ∫ x in Ioi (1 : ℝ), WeilArchimedeanIntegrandV1 (mixed p q) x from
      by simpa using (integral_comp_exp_Ioi (WeilArchimedeanIntegrandV1 (mixed p q)) 0)]
  apply setIntegral_congr_fun measurableSet_Ioi
  intro u hu
  change 0 < u at hu
  have heinv : (Real.exp u)⁻¹ = Real.exp (-u) := (Real.exp_neg u).symm
  simp only [WeilArchimedeanIntegrandV1, hzero u hu.le, hcenter,
    mul_zero, sub_zero, zero_add, Complex.real_smul, heinv,
    logCross_eq_mixed_v28, neg_div, Complex.ofReal_div, Complex.ofReal_sub,
    Complex.ofReal_one]
  apply kernel_algebra
  · simp
  · exact_mod_cast (ne_of_gt (sub_pos.mpr
      (Real.exp_lt_one_iff.mpr (by linarith))) : (1 - Real.exp (-2 * u) : ℝ) ≠ 0)
  · simp [Real.exp_neg]
  · rw [← Complex.ofReal_mul]
    congr 1
    rw [← Real.exp_add]
    congr 1
    ring
  · rw [← Complex.ofReal_mul]
    congr 1
    rw [← Real.exp_add]
    congr 1
    ring

/-- A single centred exponential subtraction works for both retained gaps. -/
theorem centered_arch_kernel_bound (u : ℝ)
    (hu : Real.log 2 - 1 / 32 ≤ u) :
    |Real.exp (-u / 2) / (1 - Real.exp (-2 * u)) -
      (6 / 5 : ℝ) * Real.exp (-u / 2)| ≤ (4 / 25 : ℝ) := by
  have hx : Real.exp (-2 * u) ≤ (4 / 15 : ℝ) := by
    have he2 : Real.exp (2 * Real.log 2) = (4 : ℝ) := by
      rw [two_mul, Real.exp_add, Real.exp_log (by norm_num : (0 : ℝ) < 2)]
      norm_num
    calc
      Real.exp (-2 * u) ≤ Real.exp (1 / 16 - 2 * Real.log 2) :=
        Real.exp_le_exp.mpr (by linarith)
      _ = Real.exp (1 / 16) / 4 := by rw [Real.exp_sub, he2]
      _ ≤ 4 / 15 := by
        linarith [AEGIS.WeilThreeBlockAnalyticConstantsV21.exp_one_over_16_upper]
  have hx0 := (Real.exp_pos (-2 * u)).le
  have hy0 := (Real.exp_pos (-u / 2)).le
  have hy4 : Real.exp (-u / 2) ^ 4 = Real.exp (-2 * u) := by
    rw [show Real.exp (-u / 2) ^ 4 =
      (Real.exp (-u / 2) * Real.exp (-u / 2)) *
      (Real.exp (-u / 2) * Real.exp (-u / 2)) by ring]
    rw [← Real.exp_add, ← Real.exp_add]
    congr 1
    ring
  have hy : Real.exp (-u / 2) ≤ (4 / 5 : ℝ) := by
    by_contra h
    have hlt : (4 / 5 : ℝ) ≤ Real.exp (-u / 2) := (lt_of_not_ge h).le
    have hh : (4 / 5 : ℝ) ^ 4 ≤ Real.exp (-u / 2) ^ 4 := by gcongr
    rw [hy4] at hh
    norm_num only [show (4 / 5 : ℝ) ^ 4 = 256 / 625 by norm_num] at hh
    linarith
  have hd : 0 < 1 - Real.exp (-2 * u) := by linarith
  have hrlo : (1 : ℝ) ≤ 1 / (1 - Real.exp (-2 * u)) := by
    apply (le_div_iff₀ hd).mpr
    linarith
  have hrhi : 1 / (1 - Real.exp (-2 * u)) ≤ (7 / 5 : ℝ) := by
    apply (div_le_iff₀ hd).mpr
    linarith
  have hr : |1 / (1 - Real.exp (-2 * u)) - (6 / 5 : ℝ)| ≤ (1 / 5 : ℝ) := by
    rw [abs_le]
    constructor <;> linarith
  calc
    |Real.exp (-u / 2) / (1 - Real.exp (-2 * u)) -
      (6 / 5 : ℝ) * Real.exp (-u / 2)| =
        Real.exp (-u / 2) * |1 / (1 - Real.exp (-2 * u)) - (6 / 5 : ℝ)| := by
      calc
        _ = |Real.exp (-u / 2) * (1 / (1 - Real.exp (-2 * u)) - (6 / 5 : ℝ))| := by
          congr 1
          ring
        _ = _ := by rw [abs_mul, abs_of_nonneg hy0]
    _ ≤ (4 / 5 : ℝ) * (1 / 5 : ℝ) := mul_le_mul hy hr (abs_nonneg _) (by norm_num)
    _ = 4 / 25 := by norm_num

/-- Integrate the centred kernel using the support-difference interval and
the actual weighted correlation moment.

Load-bearing width convention:
- each retained packet has total log-support width 1/32;
- the mixed support-difference interval has total width 1/16. -/
theorem separated_arch_norm_bound
    (p q : WeilCompactSmoothGV1) (plo phi qlo qhi E : ℝ)
    (hp : LogSupportIn p plo phi) (hq : LogSupportIn q qlo qhi)
    (hgap : Real.log 2 - 1 / 32 ≤ qlo - phi)
    (hwidth : (qhi - plo) - (qlo - phi) = CorrelationSupportDifferenceWidthV31)
    (hm : WeilMomentConditionsV1 p) (hE : 0 ≤ E)
    (hR : ∀ u : ℝ, ‖logCrossV28 p q u‖ ≤ E) :
    ‖WeilArchimedeanIntegralV1 (mixed p q)‖ ≤ (1 / 100 : ℝ) * E := by
  let lo := qlo - phi
  let hi := qhi - plo
  let K : ℝ → ℝ := fun u => Real.exp (-u / 2) / (1 - Real.exp (-2 * u))
  let F : ℝ → ℂ := fun u => (K u : ℂ) * logCrossV28 p q (-u)
  let M : ℝ → ℂ := fun u => (Real.exp (-u / 2) : ℂ) * logCrossV28 p q (-u)
  have hlo : 0 < lo := by
    dsimp [lo]
    linarith [log_two_gt_one_thirty_two]
  have hzero (u : ℝ) (hu : u ∉ Icc lo hi) : logCrossV28 p q (-u) = 0 := by
    apply logCross_zero_outside p q plo phi qlo qhi (-u) hp hq
    by_cases hlow : u < lo
    · right
      dsimp [lo] at hlow
      linarith
    · have hhigh : hi < u := lt_of_not_ge (fun h => hu ⟨le_of_not_gt hlow, h⟩)
      left
      dsimp [hi] at hhigh
      linarith
  have hFfull : (∫ u in Icc lo hi, F u) = ∫ u, F u :=
    setIntegral_eq_integral_of_forall_compl_eq_zero (fun u hu => by simp [F, hzero u hu])
  have hFpos : (∫ u in Ioi (0 : ℝ), F u) = ∫ u, F u := by
    apply setIntegral_eq_integral_of_forall_compl_eq_zero
    intro u hu
    have hnot : u ∉ Icc lo hi := by
      intro h
      exact hu (lt_of_lt_of_le hlo h.1)
    simp [F, hzero u hnot]
  have harch : WeilArchimedeanIntegralV1 (mixed p q) = ∫ u in Icc lo hi, F u := by
    rw [separated_arch_eq_log_kernel p q plo phi qlo qhi hp hq (by dsimp [lo] at hlo; linarith)]
    exact hFpos.trans hFfull.symm
  have hMfull : (∫ u, M u) = 0 := by
    have ht := integral_neg_eq_self
      (fun u : ℝ => (Real.exp (u / 2) : ℂ) * logCrossV28 p q u) volume
    exact ht.trans (logCross_plus_moment_zero p q plo phi qlo qhi hp hq hm)
  have hMzero : (∫ u in Icc lo hi, M u) = 0 := by
    rw [setIntegral_eq_integral_of_forall_compl_eq_zero (f := M) (s := Icc lo hi)
      (fun u hu => by simp [M, hzero u hu])]
    exact hMfull
  have hMc : Continuous M := by
    dsimp [M]
    exact (by fun_prop : Continuous (fun u : ℝ => (Real.exp (-u / 2) : ℂ))).mul
      ((logCross_continuous p q).comp continuous_neg)
  have hKc : ContinuousOn K (Icc lo hi) := by
    apply ContinuousOn.div (by fun_prop) (by fun_prop)
    intro u hu
    have hup : 0 < u := lt_of_lt_of_le hlo hu.1
    exact ne_of_gt (sub_pos.mpr (Real.exp_lt_one_iff.mpr (by linarith)))
  have hFc : ContinuousOn F (Icc lo hi) :=
    (Complex.continuous_ofReal.comp_continuousOn hKc).mul
      (((logCross_continuous p q).comp continuous_neg).continuousOn)
  have hcancel : (∫ u in Icc lo hi, F u) =
      ∫ u in Icc lo hi, F u - (6 / 5 : ℂ) * M u := by
    rw [integral_sub hFc.integrableOn_Icc (hMc.integrableOn_Icc.const_mul _),
      integral_const_mul, hMzero, mul_zero, sub_zero]
  have hpoint (u : ℝ) (hu : u ∈ Icc lo hi) :
      ‖F u - (6 / 5 : ℂ) * M u‖ ≤ (4 / 25 : ℝ) * E := by
    have hku := centered_arch_kernel_bound u (hgap.trans hu.1)
    have heq : F u - (6 / 5 : ℂ) * M u =
        (((K u - (6 / 5 : ℝ) * Real.exp (-u / 2)) : ℝ) : ℂ) * logCrossV28 p q (-u) := by
      dsimp [F, M]
      push_cast
      ring
    rw [heq, norm_mul, Complex.norm_real, Real.norm_eq_abs]
    exact mul_le_mul hku (hR (-u)) (norm_nonneg _) (by norm_num)
  rw [harch, hcancel]
  calc
    ‖∫ u in Icc lo hi, F u - (6 / 5 : ℂ) * M u‖ ≤
        (4 / 25 : ℝ) * E * (volume.restrict (Icc lo hi)).real univ := by
      apply norm_integral_le_of_norm_le_const
      filter_upwards [self_mem_ae_restrict measurableSet_Icc] with u hu
      exact hpoint u hu
    _ = (1 / 100 : ℝ) * E := by
      have hw : hi - lo = (1 / 16 : ℝ) := by
        simpa [CorrelationSupportDifferenceWidthV31] using hwidth
      simp [Measure.real, Real.volume_Icc, hw]
      <;> ring

theorem translated_arch_norm_bound
    (g : WeilCompactSmoothGV1) (a d1 d2 : ℝ)
    (hw : WidthOneThirtyTwoAt g a) (hm : WeilMomentConditionsV1 g)
    (hd : Real.log 2 ≤ d2 - d1) :
    ‖WeilArchimedeanIntegralV1 (mixed (translatePacket g d1) (translatePacket g d2))‖ ≤
      (1 / 100 : ℝ) * AEGIS.WeilDisjointEnergyV2.energy g.1 := by
  apply separated_arch_norm_bound (translatePacket g d1) (translatePacket g d2)
    (a - 1 / 64 + d1) (a + 1 / 64 + d1)
    (a - 1 / 64 + d2) (a + 1 / 64 + d2)
    (AEGIS.WeilDisjointEnergyV2.energy g.1)
  · exact translate_logSupportIn g d1 _ _ hw
  · exact translate_logSupportIn g d2 _ _ hw
  · linarith
  · norm_num [CorrelationSupportDifferenceWidthV31]
    ring
  · exact translate_preserves_moments g d1 hm
  · exact AEGIS.WeilDisjointEnergyV2.energy_nonnegative g.1
  · intro u
    rw [logCross_translate_eq_logCorrelation_v28]
    exact AEGIS.WeilWidthArchCorrelationV25.norm_logCorrelation_le_energy_v25 g _

theorem three_arch_bounds_of_moments
    (g : WeilCompactSmoothGV1) (a : ℝ)
    (hw : WidthOneThirtyTwoAt g a) (hm : WeilMomentConditionsV1 g) :
    ‖WeilArchimedeanIntegralV1 (mixed (gMinus g) (gZero g))‖ ≤
        (1 / 100 : ℝ) * AEGIS.WeilDisjointEnergyV2.energy g.1 ∧
    ‖WeilArchimedeanIntegralV1 (mixed (gMinus g) (gPlus g))‖ ≤
        (1 / 100 : ℝ) * AEGIS.WeilDisjointEnergyV2.energy g.1 ∧
    ‖WeilArchimedeanIntegralV1 (mixed (gZero g) (gPlus g))‖ ≤
        (1 / 100 : ℝ) * AEGIS.WeilDisjointEnergyV2.energy g.1 := by
  refine ⟨translated_arch_norm_bound g a (-Real.log 2) 0 hw hm (by linarith), ?_, ?_⟩
  · exact translated_arch_norm_bound g a (-Real.log 2) (Real.log 2) hw hm
      (by linarith [Real.log_nonneg (by norm_num : (1 : ℝ) ≤ 2)])
  · exact translated_arch_norm_bound g a 0 (Real.log 2) hw hm (by linarith)

theorem three_cross_bounds_of_moments
    (g : WeilCompactSmoothGV1) (a : ℝ)
    (hw : WidthOneThirtyTwoAt g a) (hm : WeilMomentConditionsV1 g) :
    ‖AEGIS.WeilMixedAlgebraV2.B (gMinus g) (gZero g)‖ ≤
        (51 / 100 : ℝ) * AEGIS.WeilDisjointEnergyV2.energy g.1 ∧
    ‖AEGIS.WeilMixedAlgebraV2.B (gMinus g) (gPlus g)‖ ≤
        (9 / 25 : ℝ) * AEGIS.WeilDisjointEnergyV2.energy g.1 ∧
    ‖AEGIS.WeilMixedAlgebraV2.B (gZero g) (gPlus g)‖ ≤
        (51 / 100 : ℝ) * AEGIS.WeilDisjointEnergyV2.energy g.1 := by
  obtain ⟨h01, h02, h12⟩ := three_arch_bounds_of_moments g a hw hm
  exact AEGIS.WeilThreeBlockCrossAssemblyV30.three_cross_bounds_of_arch g a hw h01 h02 h12

theorem three_block_bound_of_moments
    (g : WeilCompactSmoothGV1) (a : ℝ)
    (hw : WidthOneThirtyTwoAt g a) (hm : WeilMomentConditionsV1 g)
    (z0 z1 z2 : ℂ) :
    (WeilExplicitRightSideV1 (WeilAutocorrelationV1
      (AEGIS.WeilMixedAlgebraV2.combo z0 z1 z2 (gMinus g) (gZero g) (gPlus g)))).re ≤
      -(1 / 10 : ℝ) * AEGIS.WeilDisjointEnergyV2.energy
        (AEGIS.WeilMixedAlgebraV2.combo z0 z1 z2 (gMinus g) (gZero g) (gPlus g)).1 := by
  obtain ⟨h01, h02, h12⟩ := three_arch_bounds_of_moments g a hw hm
  exact AEGIS.WeilThreeBlockCrossAssemblyV30.three_block_bound_of_arch
    g a hw z0 z1 z2 h01 h02 h12

end AEGIS.WeilSeparatedArchBridgeV31

#print axioms AEGIS.WeilSeparatedArchBridgeV31.twice_packet_width_eq_correlation_width_v31
#print axioms AEGIS.WeilSeparatedArchBridgeV31.weightedCrossIntegrand_integrable
#print axioms AEGIS.WeilSeparatedArchBridgeV31.weighted_logCross_integrable
#print axioms AEGIS.WeilSeparatedArchBridgeV31.weighted_logCross_moment_zero
#print axioms AEGIS.WeilSeparatedArchBridgeV31.logCross_plus_moment_zero
#print axioms AEGIS.WeilSeparatedArchBridgeV31.logCross_minus_moment_zero
#print axioms AEGIS.WeilSeparatedArchBridgeV31.separated_arch_eq_log_kernel
#print axioms AEGIS.WeilSeparatedArchBridgeV31.centered_arch_kernel_bound
#print axioms AEGIS.WeilSeparatedArchBridgeV31.separated_arch_norm_bound
#print axioms AEGIS.WeilSeparatedArchBridgeV31.translated_arch_norm_bound
#print axioms AEGIS.WeilSeparatedArchBridgeV31.three_arch_bounds_of_moments
#print axioms AEGIS.WeilSeparatedArchBridgeV31.three_cross_bounds_of_moments
#print axioms AEGIS.WeilSeparatedArchBridgeV31.three_block_bound_of_moments
