import Mathlib.Topology.Instances.AddCircle.DenseSubgroup
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Algebra.Group.Nat.Even
import Mathlib.Algebra.Ring.Parity
import Mathlib.Tactic

open Set

set_option autoImplicit false

namespace RHSnowflakeLog23

/-- The logarithmic scales supplied by the dyadic and Eisenstein/hexagonal
lanes are rationally independent.  The proof is elementary: a rational
relation would force a positive power of 2 to equal a positive power of 3. -/
theorem irrational_log_two_div_log_three :
    Irrational (Real.log 2 / Real.log 3) := by
  intro hrat
  rcases hrat with ⟨q, hq⟩
  have hlog2 : 0 < Real.log (2 : ℝ) := Real.log_pos (by norm_num)
  have hlog3 : 0 < Real.log (3 : ℝ) := Real.log_pos (by norm_num)
  have hratio : 0 < Real.log (2 : ℝ) / Real.log (3 : ℝ) :=
    div_pos hlog2 hlog3
  have hqposR : (0 : ℝ) < (q : ℝ) := by
    rw [hq]
    exact hratio
  have hqpos : 0 < q := by exact_mod_cast hqposR
  have hnumpos : 0 < q.num := Rat.num_pos.mpr hqpos
  have hdenR : (q.den : ℝ) ≠ 0 := by
    exact_mod_cast q.den_ne_zero
  have hlog3ne : Real.log (3 : ℝ) ≠ 0 := ne_of_gt hlog3
  have hqcast :
      ((q.num : ℤ) : ℝ) / (q.den : ℝ) =
        Real.log (2 : ℝ) / Real.log (3 : ℝ) := by
    simpa [Rat.cast_def] using hq
  have hcross :
      ((q.num : ℤ) : ℝ) * Real.log (3 : ℝ) =
        Real.log (2 : ℝ) * (q.den : ℝ) :=
    (div_eq_div_iff hdenR hlog3ne).mp hqcast
  have hnumAbsInt : (q.num.natAbs : ℤ) = q.num :=
    Int.natAbs_of_nonneg hnumpos.le
  have hnumAbsR : (q.num.natAbs : ℝ) = ((q.num : ℤ) : ℝ) := by
    exact_mod_cast hnumAbsInt
  have hlogpow :
      Real.log ((2 : ℝ) ^ q.den) =
        Real.log ((3 : ℝ) ^ q.num.natAbs) := by
    rw [Real.log_pow, Real.log_pow, hnumAbsR]
    nlinarith [hcross]
  have heqR : (2 : ℝ) ^ q.den = (3 : ℝ) ^ q.num.natAbs :=
    Real.log_injOn_pos
      (Set.mem_Ioi.mpr (by positivity))
      (Set.mem_Ioi.mpr (by positivity))
      hlogpow
  have heqN : 2 ^ q.den = 3 ^ q.num.natAbs := by
    exact_mod_cast heqR
  have heven : Even (2 ^ q.den) := by
    rw [Nat.even_pow]
    exact ⟨by norm_num, q.den_ne_zero⟩
  have hodd : Odd (3 ^ q.num.natAbs) :=
    (show Odd (3 : ℕ) by norm_num).pow
  have hoddL : Odd (2 ^ q.den) := by
    rw [heqN]
    exact hodd
  exact (Nat.not_even_iff_odd.mpr hoddL) heven

/-- The additive subgroup generated by the two logarithmic prime scales. -/
def SnowflakeShiftGroup : AddSubgroup ℝ :=
  AddSubgroup.closure {Real.log 2, Real.log 3}

/-- The dyadic + hexagonal shift group is dense in the real log-coordinate
line.  This is the topological ingredient absent from the dyadic tower alone. -/
theorem snowflake_shift_group_dense :
    Dense (SnowflakeShiftGroup : Set ℝ) := by
  simpa [SnowflakeShiftGroup] using
    (dense_addSubgroupClosure_pair_iff.mpr irrational_log_two_div_log_three)

#print axioms RHSnowflakeLog23.irrational_log_two_div_log_three
#print axioms RHSnowflakeLog23.snowflake_shift_group_dense

end RHSnowflakeLog23
