/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import Mathlib.Topology.Instances.AddCircle.DenseSubgroup
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Algebra.Group.Nat.Even
import Mathlib.Algebra.Ring.Parity
import Mathlib.Tactic

/-!
# RH snowflake log-2/log-3 globalization bridge

This file proves the arithmetic-topological part of a candidate globalization
lane for the Riemann Hypothesis formalization: the logarithmic scales generated
by 2 and 3 are rationally independent, hence the additive subgroup they
generate is dense in the real log-coordinate line.

This is not itself a proof of the Riemann Hypothesis.  Its intended use is to
combine the existing dyadic translation tower with a second, hexagonal/
Eisenstein scale before proving continuity and positivity closure on finite
log-windows.
-/

open Set

set_option autoImplicit false

namespace RHSnowflakeLog23

/-- The logarithmic scales supplied by the dyadic and Eisenstein/hexagonal
lanes are rationally independent.  The proof is elementary: a rational
relation would force a positive power of 2 to equal a positive power of 3. -/
theorem irrational_log_two_div_log_three :
    Irrational (Real.log 2 / Real.log 3) := by
  intro hrat
  rcases hrat with ⟨q, hq⟩
  have hlog2 : 0 < Real.log (2 : ℝ) := Real.log_pos (by norm_num)
  have hlog3 : 0 < Real.log (3 : ℝ) := Real.log_pos (by norm_num)
  have hratio : 0 < Real.log (2 : ℝ) / Real.log (3 : ℝ) :=
    div_pos hlog2 hlog3
  have hqposR : (0 : ℝ) < (q : ℝ) := by
    rw [hq]
    exact hratio
  have hqpos : 0 < q := by exact_mod_cast hqposR
  have hnumpos : 0 < q.num := Rat.num_pos.mpr hqpos
  have hdenR : (q.den : ℝ) ≠ 0 := by
    exact_mod_cast q.den_ne_zero
  have hlog3ne : Real.log (3 : ℝ) ≠ 0 := ne_of_gt hlog3
  have hqcast :
      ((q.num : ℤ) : ℝ) / (q.den : ℝ) =
        Real.log (2 : ℝ) / Real.log (3 : ℝ) := by
    simpa [Rat.cast_def] using hq
  have hcross :
      ((q.num : ℤ) : ℝ) * Real.log (3 : ℝ) =
        Real.log (2 : ℝ) * (q.den : ℝ) :=
    (div_eq_div_iff hdenR hlog3ne).mp hqcast
  have hnumAbsInt : (q.num.natAbs : ℤ) = q.num :=
    Int.natAbs_of_nonneg hnumpos.le
  have hnumAbsR : (q.num.natAbs : ℝ) = ((q.num : ℤ) : ℝ) := by
    exact_mod_cast hnumAbsInt
  have hlogpow :
      Real.log ((2 : ℝ) ^ q.den) =
        Real.log ((3 : ℝ) ^ q.num.natAbs) := by
    rw [Real.log_pow, Real.log_pow, hnumAbsR]
    nlinarith [hcross]
  have heqR : (2 : ℝ) ^ q.den = (3 : ℝ) ^ q.num.natAbs :=
    Real.log_injOn_pos
      (Set.mem_Ioi.mpr (by positivity))
      (Set.mem_Ioi.mpr (by positivity))
      hlogpow
  have heqN : 2 ^ q.den = 3 ^ q.num.natAbs := by
    exact_mod_cast heqR
  have heven : Even (2 ^ q.den) := by
    rw [Nat.even_pow]
    exact ⟨by norm_num, q.den_ne_zero⟩
  have hodd : Odd (3 ^ q.num.natAbs) :=
    (show Odd (3 : ℕ) by norm_num).pow
  have hoddL : Odd (2 ^ q.den) := by
    rw [heqN]
    exact hodd
  exact (Nat.not_even_iff_odd.mpr hoddL) heven

/-- The additive subgroup generated by the two logarithmic prime scales. -/
def SnowflakeShiftGroup : AddSubgroup ℝ :=
  AddSubgroup.closure {Real.log 2, Real.log 3}

/-- The dyadic + hexagonal shift group is dense in the real log-coordinate
line.  This is the topological ingredient absent from the dyadic tower alone. -/
theorem snowflake_shift_group_dense :
    Dense (SnowflakeShiftGroup : Set ℝ) := by
  simpa [SnowflakeShiftGroup] using
    (dense_addSubgroupClosure_pair_iff.mpr irrational_log_two_div_log_three)

/-- A continuous real-valued quantity that is nonnegative on the snowflake
shift group is nonnegative everywhere.  This is the exact closure principle
needed once a translation-kernel quadratic value is shown continuous. -/
theorem snowflake_nonnegative_of_continuous
    (Q : ℝ → ℝ) (hQ : Continuous Q)
    (hnonneg : ∀ x : ℝ, x ∈ SnowflakeShiftGroup → 0 ≤ Q x) :
    ∀ x : ℝ, 0 ≤ Q x := by
  have hclosed : IsClosed {x : ℝ | 0 ≤ Q x} :=
    isClosed_Ici.preimage hQ
  have hsub : (SnowflakeShiftGroup : Set ℝ) ⊆ {x : ℝ | 0 ≤ Q x} := by
    intro x hx
    exact hnonneg x hx
  have hclosure :
      closure (SnowflakeShiftGroup : Set ℝ) ⊆ {x : ℝ | 0 ≤ Q x} :=
    closure_minimal hsub hclosed
  intro x
  apply hclosure
  simpa [snowflake_shift_group_dense.closure_eq]

#print axioms RHSnowflakeLog23.irrational_log_two_div_log_three
#print axioms RHSnowflakeLog23.snowflake_shift_group_dense
#print axioms RHSnowflakeLog23.snowflake_nonnegative_of_continuous

end RHSnowflakeLog23
