/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import WeilMixedMellinFactorV10
import WeilExplicitFormulaV10
import WeilFinalSignTranslationBoundV10
import WeilActualZeroSummandWitnessV10
import Mathlib.Tactic

/-!
AEGIS Ω — translated arithmetic B as the canonical zero exponential series V10.

For a moment-zero packet g define

  a_rho(g) = m_rho M g(rho) conj(M g(1-conj rho)).

The exact translation law gives

  M(T_d g)(s) = exp((s-1/2)d) M g(s),

and the whole explicit formula applied to the mixed carrier gives

  B(g,T_d g)
    = - sum_rho a_rho(g) exp((1/2-rho)d).

This is the exact bounded exponential-series representation required by the
Laplace-pole converse.

AUTHORITY_EFFECT = NONE.
-/

open Set Filter Topology Complex MeasureTheory
open scoped BigOperators ComplexConjugate

set_option autoImplicit false
noncomputable section

namespace AEGIS.WeilTranslatedZeroSeriesV10

open AEGIS.WeilAutocorrelationMellinFactorV10
open AEGIS.WeilLogCoordinateIsometryV21
open AEGIS.WeilMixedMellinFactorV10
open AEGIS.WeilMixedClosureV2
open AEGIS.WeilMixedAlgebraV2
open AEGIS.WeilThreeBlockTranslatedPacketsV22
open AEGIS.WeilExplicitFormulaV10
open AEGIS.WeilFinalSignTranslationBoundV10

/-- Bilateral transform of a translated packet. -/
theorem logLaplace_translatePacket_v10
    (g : WeilCompactSmoothGV1) (d : ℝ) (z : ℂ) :
    logLaplaceV10 (translatePacket g d) z =
      Complex.exp (z * (d : ℂ)) * logLaplaceV10 g z := by
  unfold logLaplaceV10
  simp_rw [logLift_translate]
  let F : ℝ → ℂ := fun w =>
    Complex.exp (z * ((w + d : ℝ) : ℂ)) *
      logLift g.1 w
  have hshift :
      (∫ u : ℝ, F (u + (-d))) = ∫ u : ℝ, F u :=
    integral_add_right_eq_self F (-d)
  have hleft :
      (fun u : ℝ => F (u + (-d))) =
        (fun u : ℝ =>
          Complex.exp (z * (u : ℂ)) *
            logLift g.1 (u - d)) := by
    funext u
    dsimp [F]
    congr 2
    push_cast
    ring
  have hright :
      (fun w : ℝ => F w) =
        (fun w : ℝ =>
          Complex.exp (z * (d : ℂ)) *
            (Complex.exp (z * (w : ℂ)) *
              logLift g.1 w)) := by
    funext w
    dsimp [F]
    rw [← mul_assoc, ← Complex.exp_add]
    congr 1
    push_cast
    ring
  rw [hleft, hright] at hshift
  rw [integral_const_mul] at hshift
  simpa using hshift

/-- Exact Mellin translation law in the centered exponent. -/
theorem mellin_translatePacket_v10
    (g : WeilCompactSmoothGV1) (d : ℝ) (s : ℂ) :
    mellin (translatePacket g d).1 s =
      Complex.exp ((s - 1 / 2) * (d : ℂ)) *
        mellin g.1 s := by
  rw [← logLaplace_shift_eq_mellin_v10
        (translatePacket g d) s,
      logLaplace_translatePacket_v10,
      logLaplace_shift_eq_mellin_v10]

/-- Canonical paired coefficient attached to one zeta zero and one packet. -/
def zeroPairCoeffV10
    (g : WeilCompactSmoothGV1)
    (rho : RiemannNontrivialZeroIndexV2) : ℂ :=
  (analyticOrderNatAt riemannZeta rho.1 : ℂ) *
    (mellin g.1 rho.1 *
      conj (mellin g.1 (1 - conj rho.1)))

/-- Exponential series generated by translating the second packet. -/
def translatedZeroSeriesV10
    (g : WeilCompactSmoothGV1) (d : ℝ) : ℂ :=
  ∑' rho : RiemannNontrivialZeroIndexV2,
    zeroPairCoeffV10 g rho *
      Complex.exp (((1 / 2 : ℂ) - rho.1) * (d : ℂ))

theorem zeroPairCoeff_eq_actual_zero_summand_v10
    (g : WeilCompactSmoothGV1)
    (rho : RiemannNontrivialZeroIndexV2) :
    zeroPairCoeffV10 g rho =
      WeilZeroIndexSummandV1
        (WeilAutocorrelationV1 g) rho := by
  symm
  exact
    AEGIS.WeilActualZeroSummandWitnessV10.actual_zero_summand_eq_paired_mellin_v10
      g rho

private theorem moment_mellin_endpoints_v10
    (g : WeilCompactSmoothGV1)
    (hm : WeilMomentConditionsV1 g) :
    mellin g.1 0 = 0 ∧ mellin g.1 1 = 0 :=
  (momentConditions_iff_mellin_endpoints_v10 g).mp hm

/-- Mixed endpoint Mellin terms vanish if both input packets satisfy the
repository moment conditions. -/
theorem mixed_mellin_endpoints_zero_v10
    (a b : WeilCompactSmoothGV1)
    (ha : WeilMomentConditionsV1 a)
    (hb : WeilMomentConditionsV1 b) :
    mellin (mixed a b) 0 = 0 ∧
      mellin (mixed a b) 1 = 0 := by
  have ha' := moment_mellin_endpoints_v10 a ha
  have hb' := moment_mellin_endpoints_v10 b hb
  constructor
  · rw [mellin_mixed_factor_v10, ha'.1, zero_mul]
  · rw [mellin_mixed_factor_v10, ha'.2, zero_mul]

/-- Whole explicit formula on the mixed carrier with both endpoint terms
killed. -/
theorem B_eq_neg_mixed_zero_tsum_v10
    (a b : WeilCompactSmoothGV1)
    (ha : WeilMomentConditionsV1 a)
    (hb : WeilMomentConditionsV1 b) :
    B a b =
      - (∑' rho : RiemannNontrivialZeroIndexV2,
          WeilZeroIndexSummandV1 (mixed a b) rho) := by
  have hEF :=
    weil_compact_smooth_explicit_formula_v1
      (asPacket a b)
  have hends :=
    mixed_mellin_endpoints_zero_v10 a b ha hb
  change
    (∑' rho : RiemannNontrivialZeroIndexV2,
      WeilZeroIndexSummandV1 (mixed a b) rho) =
      mellin (mixed a b) 0 + mellin (mixed a b) 1 -
        B a b at hEF
  rw [hends.1, hends.2, zero_add, zero_sub] at hEF
  have hneg := congrArg Neg.neg hEF
  simpa using hneg.symm

/-- Pointwise translated mixed zero summand. -/
theorem translated_mixed_zero_summand_v10
    (g : WeilCompactSmoothGV1) (d : ℝ)
    (rho : RiemannNontrivialZeroIndexV2) :
    WeilZeroIndexSummandV1
        (mixed g (translatePacket g d)) rho =
      zeroPairCoeffV10 g rho *
        Complex.exp
          (((1 / 2 : ℂ) - rho.1) * (d : ℂ)) := by
  unfold WeilZeroIndexSummandV1 zeroPairCoeffV10
  rw [mellin_mixed_factor_v10]
  rw [mellin_translatePacket_v10]
  rw [map_mul, ← Complex.exp_conj]
  have hexp :
      conj
        (((1 - conj rho.1) - 1 / 2) * (d : ℂ)) =
        ((1 / 2 : ℂ) - rho.1) * (d : ℂ) := by
    rw [map_mul]
    simp only [map_sub, map_one, Complex.conj_ofReal]
    rw [Complex.conj_conj]
    ring
  rw [hexp]
  ring

/-- THE translated B exponential-series identity. -/
theorem B_translate_eq_neg_zeroSeries_v10
    (g : WeilCompactSmoothGV1)
    (hm : WeilMomentConditionsV1 g)
    (d : ℝ) :
    B g (translatePacket g d) =
      -translatedZeroSeriesV10 g d := by
  have hmt :=
    translate_preserves_moments g d hm
  rw [B_eq_neg_mixed_zero_tsum_v10 g
    (translatePacket g d) hm hmt]
  unfold translatedZeroSeriesV10
  congr 1
  apply tsum_congr
  intro rho
  exact translated_mixed_zero_summand_v10 g d rho

/-- Final sign therefore bounds the zero exponential series uniformly for all
real translations. -/
theorem translatedZeroSeries_uniform_bound_v10
    (hfinal : AEGIS.RHFinalClosureV1.FinalSignResidualV1)
    (g : WeilCompactSmoothGV1)
    (hm : WeilMomentConditionsV1 g)
    (d : ℝ) :
    ‖translatedZeroSeriesV10 g d‖ ≤
      2 * (-(B g g).re) := by
  rw [← norm_neg]
  rw [← B_translate_eq_neg_zeroSeries_v10 g hm d]
  exact
    translated_B_norm_bound_v10 hfinal g hm d

end AEGIS.WeilTranslatedZeroSeriesV10

#print axioms AEGIS.WeilTranslatedZeroSeriesV10.mellin_translatePacket_v10
#print axioms AEGIS.WeilTranslatedZeroSeriesV10.B_eq_neg_mixed_zero_tsum_v10
#print axioms AEGIS.WeilTranslatedZeroSeriesV10.B_translate_eq_neg_zeroSeries_v10
#print axioms AEGIS.WeilTranslatedZeroSeriesV10.translatedZeroSeries_uniform_bound_v10
